### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ralight** [Ghost-script/MQTT-CPP-Sample#1]
Hi there,

As far as I can see, this is just a commit of code from the mosquitto project with no modifications. The license file in the repository implies the license is GPL. This is not true, the code you have imported is dual licensed EDL/EPL.

**Comment by codenamesubho** [comment]
@ralight ,
Thanks for notifying me. So which license suits my code? Basically sample-1
folder is from mosquitto project without modification. But the sample-2
folder contains a file of my own. Also i must say this is a temporary repo either i will be removing the files or deleting the repo. I am working with MQTT and having trouble with it. So i just asked a
question on Stackoverflow and pushed the files here temporarily. I put GPL
License by default for any work i do. It will be very helpful if you could
help me deciding which license to use for my repository. Hoping to hear
from you soon.

**Comment by codenamesubho** [comment]
Removed GPL License.
